[package]
name = "chat-core"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = {version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"]}
json = "0.12"
bitflags = "1.3"
async-trait = "0.1.56"
futures-channel = "0.3"